### ISSUE TITLE
The cron job has crashed two days in a row

### ISSUE THREAD

**Issue by chrisaasan** [dotabap/dotabap-list#116]
The title pretty much sums it up I guess.

**Comment by chrisaasan** [comment]
Found this in the log, note sure if it's helpful.

Parsing MDJoerg/adele
Statement does not exist in ABAPCloud(or a parser error), "INCLUDE"
Statement does not exist in ABAPCloud(or a parser error), "INCLUDE"
Statement does not exist in ABAPCloud(or a parser error), "INCLUDE"
Statement does not exist in ABAPCloud(or a parser error), "ade_prepare_where_selopt"
Statement does not exist in ABAPCloud(or a parser error), "ade_check_selopt"
Parsing Microsoft/ABAP-SDK-for-Azure
TypeError: dd07v_tab is not iterable
Error: Process completed with exit code 1.

**Comment by larshp** [comment]
thanks

**Comment by larshp** [comment]
will be fixed with https://github.com/abaplint/abaplint/pull/2164/commits/7b806a4f12f1f05c5c7f6358ac524af6ce6135e4

**Comment by larshp** [comment]
running, https://github.com/dotabap/dotabap-list/actions/workflows/cron.yml

closing
