### ISSUE TITLE
Cron stopped after alaible/dbg_value_statement was added

### ISSUE THREAD

**Issue by chrisaasan** [dotabap/dotabap-list#127]
The log from cron

GitHub fetch ysichov/Simple-Data-Explorer
Duplicate filename, rayatus/sapbugtracker: zcl_entity.clas.abap
Duplicate filename, rayatus/sapbugtracker: zcl_entity.clas.xml
Error: Process completed with exit code 1.

I see that both rayatus/sapbugtracker and alaible/dbg_value_statement has the files zcl_entity.clas.abap and zcl_entity.clas.xml. Maybe the script can't handle duplicate file names across different projects?

**Comment by larshp** [comment]
its a feature 😁 

for the open source ecosystem, everyone would like not to have any overlapping filenames, so everything can be consumed in the same system

**Comment by chrisaasan** [comment]
Aha, I guess very generic names of objects like "entity" is bad idea then.

**Comment by larshp** [comment]
give em some days to adjust, if not might remove one or both repos from the list

**Comment by larshp** [comment]
now running, https://github.com/dotabap/dotabap-list/actions/runs/1696618679, closing
