### ISSUE TITLE
Questionable addition

### ISSUE THREAD

**Issue by marcellourbani** [dotabap/dotabap-list#13]
Wanted to add a little project of mine:
https://github.com/marcellourbani/abap_debugger_object_graph_extension

which is pretty much a better UI for https://github.com/larshp/ABAP-Object-Visualizer 

It's about 600 lines of ABAP, but my contribution is probably less than 100, not counting the JS stuff I ended up putting in a different project

**Comment by larshp** [comment]
feel free to add it 😄
