### ISSUE TITLE
Cron job crashes

### ISSUE THREAD

**Issue by chrisaasan** [dotabap/dotabap-list#134]
Looks like oliverit/express.abap has been deleted and the cron job crashes when it can't find https://github.com/oliverit/express.abap

**Comment by chrisaasan** [comment]
The same will probably apply to oliverit/json.abap

**Comment by larshp** [comment]
updated, thanks

**Comment by larshp** [comment]
cron manually triggered

**Comment by larshp** [comment]
green, https://github.com/dotabap/dotabap-list/actions/runs/2330776071
