### ISSUE TITLE
cron job failing

### ISSUE THREAD

**Issue by fleischr** [dotabap/dotabap-list#144]
Added provideplatform/proUBC last week - but not yet seeing it on dotabap.org.

Appears to have issue because the repository includes classes that use the ABAP openAPI generator for REST API connectivity

**Comment by fleischr** [comment]
Doesn't seem to be required - so I'm removing it from the package. Hopefully thereafter the job should run successfully.

**Comment by larshp** [comment]
yea, dont copy open source using the same filename into a project, this will break the ecosystem

instead, if needed, do automatic renaming into your package, https://blogs.sap.com/2021/04/20/automagic-standalone-renaming-of-abap-objects/

Example: ajson is renamed and copied into abapGit automatically, https://github.com/abapGit/abapGit/pull/5713

as for https://github.com/abap-openapi/abap-openapi, its designed so it can run on github actions generating the artifacts, ie. no need to have it in the repo, just the generated artifacts needed

**Comment by larshp** [comment]
running, green
