### ISSUE TITLE
Website currently stuck at the hour glass

### ISSUE THREAD

**Issue by MartinPankraz** [dotabap/dotabap-list#154]
Dear community,

the beloved ABAP repos list is currently stuck on page load. Would be great if you could give it a look. Seems like a data source is not supplying anticpated values.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/5108923/201888483-c923405b-ce74-4bfa-9618-d569629d2694.png">

KR
Martin

**Comment by larshp** [comment]
merged https://github.com/dotabap/dotabap-validator/pull/303 earlier today, probably somewhere around that

**Comment by larshp** [comment]
@MartinPankraz try again

fixed with https://github.com/dotabap/dotabap-generated/commit/29800e561b7964ffaf375520af64c94b56911da8

**Comment by MartinPankraz** [comment]
it is alive 🧟‍♂️again. Thanks for the prompt fix @larshp!
