### ISSUE TITLE
Some more potential relevant repos

### ISSUE THREAD

**Issue by chrisaasan** [dotabap/dotabap-list#171]
I did some searching on GitHub and found some repos that might be relevant to put on the list. I just wanted to run them by you before I added them. I'm happy to add them, I just wanted your input before I begin.

https://github.com/SAP-samples/abap-platform-fundamentals-01

https://github.com/kseretis/abap-metrics

None of these have a license, I can ask the maintainer to add a license.
https://github.com/zenrosadira/abap-tbox-random-data
https://github.com/zenrosadira/abap-tbox-stats
https://github.com/zenrosadira/abap-tbox-jobber
https://github.com/zenrosadira/abap-tbox-fmoduler
https://github.com/zenrosadira/abap-tbox-csvman
https://github.com/zenrosadira/abap-tbox-processer
https://github.com/zenrosadira/abap-tbox-lockwaiter
https://github.com/zenrosadira/abap-tbox-splitter

Tis one contains some relevant stuff, but are not really that abapgit friendly, so it could be a candidate for related.json instead?
https://github.com/SAP-samples/security-services-tools

There are also a quite a few here, and some of them could be relevant to add as well.
https://github.com/orgs/SAP-samples/repositories?q=&type=all&language=abap&sort=

**Comment by larshp** [comment]
I think its more up to the owners to decide if they like it listed or not

**Comment by chrisaasan** [comment]
Created a ticket on the repos, except for SAP, and asked them to add it to the list.
