### ISSUE TITLE
cron has failed 2 days in a row

### ISSUE THREAD

**Issue by chrisaasan** [dotabap/dotabap-list#206]
@larshp  @mbtools  it looks like there are some issue with the google repo. I'm not able to see exactly whats wrong myself.

Also, even when the cron fails, the cron icon on https://dotabap.org/ remains green.

**Comment by mbtools** [comment]
Thanks. Although it the Google repo has a `.abapGit.xml` file, it doesn't comply with standard abapGit rules.

Lars is removing it from the list.

**Comment by larshp** [comment]
@mbtools can you consider renaming https://github.com/Marc-Bernard-Tools/ABAP-Strust/blob/main/src/zcl_strust.clas.abap ? its overlapping with https://github.com/mkysoft/zstrust/blob/main/src/zcl_strust.clas.abap

**Comment by mbtools** [comment]
will do

**Comment by larshp** [comment]
temporarily removed, https://github.com/dotabap/dotabap-list/commit/12a70bc2b9fd4e833e726f8166b79fd7f6376bc0

**Comment by mbtools** [comment]
renamed

**Comment by larshp** [comment]
added back, https://github.com/dotabap/dotabap-list/commit/edf8447c075da382df1eab5c4bb822efe5d861a3
