### ISSUE TITLE
Cron has failed for the last week

### ISSUE THREAD

**Issue by chrisaasan** [dotabap/dotabap-list#211]
Looks like repo github.com/d023604/open-location-code-abap has been moved to https://github.com/andrew-barnard/open-location-code-abap

cc: @andrew-barnard 

I don't have time to fix it right now, but I can do it later tonight. 

Also, the cron label on dotabap.org seems to stay green regardless of how the job runs.

**Comment by larshp** [comment]
thanks, fixed
