### ISSUE TITLE
build fails after rename of pawelwiejkut/bw_remove_charters

### ISSUE THREAD

**Issue by abap-weasel** [dotabap/dotabap-list#221]
Errors for some days like this from https://github.com/dotabap/dotabap-list/actions/runs/11361695090/job/31601954459#step:4:2042 

GitHub fetch pawelwiejkut/bw_remove_charters
Error: Server responded to https://api.github.com/repositories/220662333 with status code 403:

Request forbidden by administrative rules. Please make sure your request has a User-Agent header (https://docs.github.com/en/rest/overview/resources-in-the-rest-api#user-agent-required). Check https://developer.github.com/ for other possible causes.

New name of repo: "pawelwiejkut/bw_remove_characters"

**Comment by larshp** [comment]
thanks, fixed with https://github.com/dotabap/dotabap-list/commit/9c1b9c642626730df441fd0845c7b45db9767ce7
