### ISSUE TITLE
ABAP Best Practice repo - 0 LOC, 50+ programming rules; is it acceptable here?

### ISSUE THREAD

**Issue by ilyakaznacheev** [dotabap/dotabap-list#31]
I'm collecting ABAP programming rules and best practices because SAP can't do that, and each company or programmer has to sample its own list.

It contains just a few lines of code as an example and doesn't compatible with abapGit (in fact, it is a single README file). But it may be very useful for ABAP community, especially for newbies and ABAP newcomers, so I would be appreciated for adding that repo to ABAP-related list.

[The repo](https://github.com/ilyakaznacheev/abap-best-practice) structured in a wiki-like manner and published under CC-BY license. It includes rules from SAP help, various SAP blogs, books, internal guidelines of different companies and my and my colleagues' experience.

**Comment by larshp** [comment]
the requirements are
"
Public repository
ABAP as primary programming language
English
Around 500+ lines of ABAP code
abapGit based
"

the page performs static analysis on each repository, this fails for non abapGit based repositories


However, I'm collecting ABAP related repositories in https://github.com/dotabap/dotabap-list/blob/master/related.json, feel free to add the project in this list. Note that there is nothing shown for this file on dotabap.org yet, its on the todo list 😄

**Comment by ilyakaznacheev** [comment]
Okay, thanks
