### ISSUE TITLE
Adding repositories from gitlab.com

### ISSUE THREAD

**Issue by gregorwolf** [dotabap/dotabap-list#66]
How can I help to get this repository:

https://gitlab.com/geertjanklaps/abap-openapi-ui

from gitlab.com added to the page?

**Comment by larshp** [comment]
currently not possible, see readme "Hosted on GitHub(more git based hosts to be added later)"

but pull request welcome

its the code in https://github.com/dotabap/dotabap-validator that runs daily to keep the list updated

**Comment by geert-janklaps** [comment]
@gregorwolf: 
I just moved the original project to GitHub and created a pull request to get ABAP OpenAPI in the list.
I think this can be closed after merging :)
